---
- name: Create containers
  include_tasks: container.yml
  loop: "{{ podman_containers }}"
  loop_control:
    loop_var: container

- name: Create pods
  include_tasks: pod.yml
  loop: "{{ podman_pods }}"
  loop_control:
    loop_var: pod
